# -*- coding: utf-8 -*-
"""Fishs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o356G0ofR5v6nSnZDYuUm95qMFjSA05_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
sns.set()

data = pd.read_csv("Fish.csv")
data

data.describe()

data.info()

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data["Species"])
data["Species"] = le.transform(data["Species"])
data.head()

data["Species"].unique()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = data.drop("Weight",axis=1)
y = data["Weight"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lr = LinearRegression()
lr.fit(X_train,y_train)

lr.score(X_train,y_train)

lr.score(X_test,y_test)

# Create a Pickle file  
import pickle
pickle_out = open("fish.pkl","wb")
pickle.dump(lr, pickle_out)
pickle_out.close()

